Card text plus d'autres truc a tester
ronde-de-l-espoir/main pull request #67
Opened 2023-04-06 20:19 UTC by Bombcreeper

2023-04-06 20:54 UTC, Skyman-2 requested changes
Are you joking? There's a conflict in just 2 commits

2023-04-07 05:23 UTC, Silloky requested changes
@Bombcreeper revert ton dernier commit car je m'en étais déjà occupé vers 20h (c'est justement la PR #65 qu'a accepté @Skyman-2 hier soir)
Sinon le reste me semble OK, mais j'ai pas vérifié.

2023-04-07 05:25 UTC, Silloky submitted a review, later dismissed
Everything seems OK

2023-04-07 05:30 UTC, Silloky requested changes
@Bombcreeper revert ton dernier commit car je m'en étais déjà occupé vers 20h (c'est justement la PR https://github.com/ronde-de-l-espoir/main/pull/65 qu'a accepté @Skyman-2 hier soir)
Sinon le reste me semble OK, mais j'ai pas vérifié.

2023-04-18 11:30 UTC, Silloky approved these changes

2023-04-18 11:31 UTC, Silloky approved these changes
This is all OK

2023-04-18 11:31 UTC, merged